version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - task-service
    environment:
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=3001
      - TASK_SERVICE_HOST=task-service
      - TASK_SERVICE_PORT=3002
    networks:
      - my-network

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
    networks:
      - my-network

  task-service:
    build: ./task-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
    networks:
      - my-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
